export { default as AboutAsoma } from './AboutAsoma'
export { default as ActionAsoma } from './ActionAsoma'
export { default as Connect } from './Connect'
export { default as CoreFeatures } from './CoreFeatures'
export { default as Facts } from './Facts'
export { default as Hero } from './Hero'
export { default as Testimonials } from './Testimonials'